### ISSUE TITLE
Explain how delegation by pool owners differ from delegation by pool stakers?

### ISSUE THREAD

**Issue by benapetr** [cardano-foundation/docs-cardano-org#48]
In https://github.com/cardano-foundation/docs-cardano-org/blob/main/explore-cardano/understanding-pledging-and-rewards.md is this statement:

> Remember that the pledge is declared during pool registration, (alongside the cost and margin values), and has to be honored by the pool owners who are delegating to the pool: If they collectively delegate less than the declared pledge, pool rewards for that epoch will be zero.

How does the network know which wallets that delegate to a pool belong to "pool owners"? Say I set up a pool, I configure the pledge parameter to 100k and once pool is visible in daedalus wallet, I delegate to it my wallet with > 100k ADA. How does the network know that I am the pool owner in order to confirm that pledge is fullfilled? Or does the ADA for pledge need to be present on some wallet associated directly with the pool? How can I make such association?

This is somewhat confusing right now. Can someone with better insight clear this up? From network point of view who is "pool owner" how is their wallet identified? Or is the pledge also fullfilled when the sum of all staked ADA by all delegators is higher than pledged value? Therefore being rather irrelevant if staked ADA really belongs to pool owners or not?

**Comment by benapetr** [comment]
https://www.reddit.com/r/cardano/comments/lka75v/how_does_the_network_determine_if_pledge_is/

> Pledge needs to be in the registered wallet that is on the pool registration. If the value falls below that of what is on the registration rewards are forfeit for the pool if it generates blocks.

**Comment by benapetr** [comment]
Might be helpful if the statement was corrected so that "pool owners" are replaced with "pool's registered wallet", but I will leave this decision on whoever maintains this documentation

**Comment by nahern** [comment]
thank you for your feedback on this. We are looking into improving this section and will clarify.
