### ISSUE TITLE
Code display issue

### ISSUE THREAD

**Issue by Rudoww** [cardano-foundation/docs-cardano-org#49]
Hi,

I hope I am writing in the correct place.
On this page ([link](https://docs.cardano.org/en/latest/marlowe/marlowe-lang-guide.html)) code snippets do not show properly in section:
- What does a Marlowe contract look like?
- Sample Escrow Contract

I have reproduced this issue in Google Chrome, Firefox, Safari and Brave.
I have attached screenshots for reference.

**Issue#1**
<img width="1439" alt="Cardano Doc - Issue1" src="https://user-images.githubusercontent.com/52272454/108030910-ebcf2e80-706a-11eb-9ede-1160feebb82a.png">

**Issue#2**
<img width="1400" alt="Cardano Doc - Issue2" src="https://user-images.githubusercontent.com/52272454/108030924-f1c50f80-706a-11eb-8e23-1de6f3b1a16b.png">

**Comment by nahern** [comment]
thanks for your feedback, we are working on fixing this.

**Comment by nahern** [comment]
this code display issue has been updated, thank you.
