### ISSUE TITLE
Pledging and rewards

### ISSUE THREAD

**Issue by brouwerQ** [cardano-foundation/docs-cardano-org#59]
Can you please update the page 'Pledging and rewards' with the following two items:

- In the formula f(s,sigma) sigma stands for relative total stake and in the formula beta/sigma, sigma stands for relative active stake.
- The monetary expansion is adjusted by min(1, èta).

I've spend a lot of time figuring out why my calculations didn't match the real rewards my pool got, and those two things (especially the first one), were the problem. Only after stumbling upon the document at https://hydra.iohk.io/build/5737201/download/1/delegation_design_spec.pdf, all was suddenly clear.

Thank you!

**Comment by tcosmo** [comment]
I encountered exactly the same issue...

https://github.com/cardano-foundation/docs-cardano-org/issues/77

Maybe we should just submit a PR?
