### ISSUE TITLE
Consider adding redirects for old links in search engines/bookmarks that are now all 404s

### ISSUE THREAD

**Issue by DanTup** [cardano-foundation/docs-cardano-org#78]
Pretty much anything I search for in the docs the last few days results in 404s. For example if I search for "cardano plutus docs" the top result is https://docs.cardano.org/projects/plutus/en/latest/ which is now a 404.

If URLs have to change, it'd be nice to have redirects for all the people with bookmarks or searching. It's significantly harder to find docs now (especially as the site doesn't seem to have its own search functionality).

**Comment by AstroWa3l** [comment]
PLEASE do this, I mean this is just common web practice at this point. I hope this gets resolved. Really messing with not just me and other members of Cardano, but you are hurting yourself as a company from reaching the general public.

**Comment by sublayerio** [comment]
@AstroWa3l Well, at least the 404 is looking great https://docs.cardano.org/projects/plutus/en/latest/

**Comment by katomm** [comment]
Valid point @DanTup, thanks! but it needs to be flagged here: https://github.com/input-output-hk/cardano-documentation/issues because this repo is no longer connected to docs.cardano.org and will be archived.

**Comment by DanTup** [comment]
I've opened https://github.com/input-output-hk/cardano-documentation/issues/25. Thanks!
